// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFhsWJG7wZk4-5OL_dOpTdNaRQfF8bdf0',
    appId: '1:849488909222:web:f4e1a3e09dfcbb2d32b567',
    messagingSenderId: '849488909222',
    projectId: 'sermanos-fe867',
    authDomain: 'sermanos-fe867.firebaseapp.com',
    storageBucket: 'sermanos-fe867.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgWoJQ7BMRCt3DHuI5FKOWv8UmfS8z1Wc',
    appId: '1:849488909222:android:98e68ccff075d09f32b567',
    messagingSenderId: '849488909222',
    projectId: 'sermanos-fe867',
    storageBucket: 'sermanos-fe867.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCT5zUJohuM0i6tNBHF1fv5XipsJkN27Y',
    appId: '1:849488909222:ios:db08463bf1cce5fe32b567',
    messagingSenderId: '849488909222',
    projectId: 'sermanos-fe867',
    storageBucket: 'sermanos-fe867.appspot.com',
    iosBundleId: 'com.example.serManos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCT5zUJohuM0i6tNBHF1fv5XipsJkN27Y',
    appId: '1:849488909222:ios:4ba40e4af3bd619c32b567',
    messagingSenderId: '849488909222',
    projectId: 'sermanos-fe867',
    storageBucket: 'sermanos-fe867.appspot.com',
    iosBundleId: 'com.example.serManos.RunnerTests',
  );
}
